version: "3.5"

services:
  api:
    hostname: api
    build:
      context: ./
      dockerfile: docker/api.Dockerfile
    volumes:
      - ./notipy:/opt/notipy
    ports:
      - 8081:8080
    depends_on:
      - redis
      - db
  redis:
    hostname: redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
  db:
    hostname: db
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: notipy
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  default:
    driver: bridge